### ISSUE TITLE
[adblocker-electron] Application is extremely lagged (memory leak)

### ISSUE THREAD

**Issue by JellyBrick** [ghostery/adblocker#3420]
https://github.com/ghostery/adblocker/commit/7782d6796da9e8f3c69c241e1b4906773db26375
Performance regression occurred after that commit.

(This issue does not occur in versions `1.26.3` and earlier)

# Code

https://github.com/organization/youtube-music-next/blob/feat/typescript/plugins/adblocker/blocker.ts

# Related issues

https://github.com/th-ch/youtube-music/issues/1187
https://github.com/th-ch/youtube-music/issues/1208
https://github.com/th-ch/youtube-music/issues/1212

**Comment by remusao** [comment]
Hi @JellyBrick,

Thanks for reaching out and sorry for the delay in answering. This looks like a serious issue and multiple people have already encountered it. At the moment I have limited bandwidth (and limited knowledge about Electron stack) so I am not able to investigate it myself. I'm gonna ping a few people who are familiar with it in the hope that we can get some clarity regarding the root cause of the slow-down.

@DrRoot-github since you opened the PR and are most likely the person with most insights in the change, would you have some availability to look into it? I believe @Jelmerro also investigated as part of the [issue on Vieb-side](https://github.com/Jelmerro/Vieb/issues/514).

Could this issue be caused by using `sendSync` from the page? Alternatively, maybe we are returning too much on updates (e.g. maybe we wrongly return scriplets or too many selectors).

I hope that helps,

**Comment by DrRoot-github** [comment]
I'll try to investigate a bit more, so please wait a little longer. If possible, it would be helpful if you could provide specific instructions on how to reproduce it. I think I might be the culprit, seriously sorry.

**Comment by remusao** [comment]
@DrRoot-github No worries at all, I think I found the issue and created a PR to fix it here: https://github.com/ghostery/adblocker/pull/3441 Would you have time to review it and maybe test that the blocking of ads in YouTube didn't regress? (from some local testing it seems fine).

Cc @Jelmerro once reviewed we can publish an update of the adblocker package (as early as today if anyone has time to review the changeset).

**Comment by KunaPrime** [comment]
I'm user of Vieb and @Jelmerro have provided me a patch with a fix (i assume it i s based on #3441) and i can confirm that regression is gone.

**Comment by remusao** [comment]
Thank you @KunaPrime and @Jelmerro, I have merged the PR and a new release will be available shortly.

**Comment by remusao** [comment]
The release pipeline got broken by some upstream dependency updates. Until it gets fixed, I have pushed a canary release manually which you can try out: https://www.npmjs.com/package/@cliqz/adblocker-electron/v/1.26.7--canary.50688cf.0

**Comment by JellyBrick** [comment]
This issue still occurs. (although to a lesser extent than before)

**Comment by remusao** [comment]
Could you provide some more details about this please?

**Comment by JellyBrick** [comment]
I can't give a definitive answer because I'm still testing, but I found the problem that the responsiveness of the webpage has decreased over time.

Tested webpage: https://music.youtube.com
